application:
  logo: VulnerableAppCTF_Logo.png
  favicon: favicon_ctf.ico
  showVersionNumber: false
  showGitHubLinks: false
  localBackupEnabled: false
  welcomeBanner:
    showOnFirstStart: false
challenges:
  showHints: false
  safetyMode: disabled
  showFeedbackButtons: false
