application:
  domain: mozilla-ctf.op
  name: 'Mozilla CTF'
  logo: 'https://github.com/mozilla/ctf-austin/raw/master/app/public/images/MozillaCTF.png'
  favicon: 'https://github.com/mozilla/ctf-austin/raw/master/app/public/favicon_v2.ico'
  theme: deeporange-indigo
  showGitHubLinks: true
  localBackupEnabled: false
  altcoinName: Mozquito
  privacyContactEmail: 'donotreply@mozilla-ctf.op'
  customMetricsPrefix: mozctf
  chatBot:
    name: 'Foxy'
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Fennec_Fox_Vulpes_zerda.jpg'
  social:
    blueSkyUrl: null
    mastodonUrl: null
    twitterUrl: 'https://twitter.com/mozcloudsec'
    facebookUrl: null
    slackUrl: null
    redditUrl: null
    pressKitUrl: 'https://blog.mozilla.org/press/kits'
    nftUrl: null
    questionnaireUrl: null
  recyclePage:
    topProductImage: Gear-200155340.jpg
    bottomProductImage: Gear-200155753.jpg
  welcomeBanner:
    showOnFirstStart: false
  cookieConsent:
    message: 'This website uses a myriad of 3rd-party cookies for your convenience and tracking pleasure.'
    dismissText: 'Never mind!'
    linkText: 'How can I turn this off?'
    linkUrl: 'https://support.mozilla.org/en-US/kb/disable-third-party-cookies'
  securityTxt:
    contact: 'mailto:donotreply@mozilla-ctf.op'
    encryption: ~
challenges:
  showHints: false
  codingChallengesEnabled: never
  xssBonusPayload: '<iframe width="560" height="315" src="https://www.youtube.com/embed/0u9g0LhRkGk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
  showFeedbackButtons: false
